

target: compile

compile:
	gcc server.c -o server -lrt -lpthread
	gcc client.c -o client -lrt -lpthread


clean:
	rm -f server
	rm -f client
	rm -f *.o
	rm -f *.out
	rm -f *.txt
	rm -f *.log
	rm -f *.bin
	rm -f *.dat
	rm -f *.pipe
	rm -f *.sock
	rm -f *.fifo
	rm -f *.shm
	
